<?php
$title = 'Edit Your Blog';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('blog/default', array('action' => 'edit', 'id' => $this->id,)));
$form->prepare();

echo $this->form()->openTag($form);

?>
<?php echo $this->formHidden($form->get('id')); ?>
    <h5>Title : </h5><?php echo $this->formRow($form->get('title')); ?>
    <h5>Description : </h5><?php echo $this->formRow($form->get('description')); ?>
    <br>
    <br>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

