<?php

$title = 'Blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('blog/default', array('action' => 'userBlogs')); ?>">My Blogs</a>
</p>

<?php foreach ($blogs as $blog) : ?>

    <h5 class="card-header"><?php echo $this->escapeHtml($blog->getTitle()); ?></h5>
    <div class="card">
        <?php echo $this->escapeHtml($blog->getDescription()); ?>
    </div>
    <br>

<?php endforeach; ?>